name: greeting

on: [push, workflow_dispatch]

jobs: 
  Test:
    # using runs-on, we can specify the operating system on which the job will run
    runs-on: ubuntu-latest
    steps: 
      - name: "clone code"

      # We use | to write multiple lines of code
      # We use ${{ }} to access the context of the workflow
      # We use toJson() to convert the context to JSON format
      # Right now We are manually cloning our code into the ubuntu-latest OS Platform.
        
#        run: |
#         echo "Cloning Repository.."
#          echo "${{toJson(github)}}"
#          git clone https://github.com/${{github.repository}}.git

      # We can use the actions/checkout@v2 action to clone the repository.
        uses: actions/checkout@v2
      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: print node version
        run: node -v

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test